### ISSUE TITLE
Program type already present: android.support.design.widget.CoordinatorLayout$1

### ISSUE THREAD

**Issue by daleiyinsi** [eleme/UETool#18]
Program type already present: android.support.design.widget.CoordinatorLayout$1

**Comment by JeasonWong** [comment]
Maybe you should force your library version，please refer to this answer : [Duplicate entry: android/support/design/widget/CoordinatorLayout
](https://stackoverflow.com/questions/49496941/duplicate-entry-android-support-design-widget-coordinatorlayout?noredirect=1&lq=1)
