### ISSUE TITLE
出现了两个悬浮窗

### ISSUE THREAD

**Issue by ordinaryX** [eleme/UETool#33]
#### Description

只使用了UETool.showUETMenu();这个方法在application中，
之前一直是正常的，就昨天突然变成了两个悬浮窗。暂时还未找到原因，
其中一个悬浮窗可用，另一个不可用。

**Comment by JeasonWong** [comment]
application 的哪个方法？是不是因为你 app 有多进程导致 showUETMenu 触发了两次？

**Comment by ordinaryX** [comment]
onCreate中，
是的，查到了，
一开始也是一直怀疑是多进程问题，但是项目里自己代码确实没多进程，刚想起来昨天集成了极光，它里边有个pushcore的进程。
应该是这个了。
