### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.facebook.drawee.view.DraweeView" on path: DexPathList

### ISSUE THREAD

**Issue by hsBoysLove** [eleme/UETool#48]
#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by hsBoysLove** [comment]
debugImplementation 'me.ele:uetool:1.0.15'
    releaseImplementation 'me.ele:uetool-no-op:1.0.15'
    // if you want to show more attrs about Fresco's DraweeView
    debugImplementation 'me.ele:uetool-fresco:1.0.15'

**Comment by hsBoysLove** [comment]
sorry,不用facebook就可以了

**Comment by JeasonWong** [comment]
嗯，当你业务了使用了 fresco 才需要依赖 `me.ele:uetool-fresco`
