### ISSUE TITLE
布局控件叠层比较多的时候，貌似没办法选择自己想要的，需要知道控件id才行

### ISSUE THREAD

**Issue by yrickwong** [eleme/UETool#49]
#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by yrickwong** [comment]
我的主页是  tabhost+viewpager这种，然后 main布局里面 有层级嵌套的关系，无法直接选中自己能看到的控件

**Comment by JeasonWong** [comment]
实在无法选中时建议使用“捕捉控件”中的“ValidViews”
