### ISSUE TITLE
Android 9.0 无法捕捉控件。

### ISSUE THREAD

**Issue by ordinaryX** [eleme/UETool#50]
提示：dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
机型：小米MIX2S
could not found view

**Comment by JeasonWong** [comment]
请问用跑下 demo 是否能正常 work ？

**Comment by ordinaryX** [comment]
#28 感觉和这个问题差不多，demo跑了，项目中也一直在用，平时都是正常的，前些天手机升了下系统，不能用了。

**Comment by JeasonWong** [comment]
@ordinaryX 可以使用 `me.ele:uetool:1.0.16`，之前反射的某个变量在 P 上被禁用了

**Comment by LiangYan2017** [comment]
请问下 我也碰到这个问题 请问是怎么解决的  谢谢

**Comment by ordinaryX** [comment]
> @ordinaryX 可以使用 `me.ele:uetool:1.0.16`，之前反射的某个变量在 P 上被禁用了
@LiangYan2017
