### ISSUE TITLE
通过多次断点试验，activity-alias模式下的activity不起作用

### ISSUE THREAD

**Issue by qiushui95** [eleme/UETool#53]
给后面的人看看同样的问题的看看。

**Comment by JeasonWong** [comment]
我在 demo 工程里加了 activity-alias ，没发现你说的问题，你可以试试哈。

**Comment by qiushui95** [comment]
@JeasonWong ` 
<application
        android:name="me.ele.uetool.sample.AppContext"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name="MainActivity"/>
        <activity
            android:name="SecondActivity"
            android:label="@string/title_activity_second"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"/>

        <activity-alias
            android:name="SecondActivityAlias"
            android:targetActivity="MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

    </application>
`
