### ISSUE TITLE
希望可以整成一个xposed插件。

### ISSUE THREAD

**Issue by qssq** [eleme/UETool#62]
### Issue Description
我发现这里面大量依赖了资源文件，或者依赖创建新的activity,不方便改造xposed插件额。
改了一点点改不动了，资源id太多了，感觉是不是要把插件的资源和他的资源（反射替换reasource?）进行合并才能解决这个问题，不然改起来太蛋疼了，得把所有findbyid都改一下啥的。。
#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by qssq** [comment]
能力不行，搞倒是搞定了，就是创建了多个，我这个是依赖activity的，没申请权限。

**Comment by longshihan1** [comment]
可以实现的，有个大佬将virtualAPP集成了UETool，里面的核心就是跨进程和源码细节的调整，实现一个插件并不复杂

**Comment by qssq** [comment]
我已经实现过了我的插件叫hookui,，没想到现在有更新了，我估计又要移植进去了，其实我的意思是兼容性增强一点点，。比如自定义设置resource,这样我升级代码不需要改。
