### ISSUE TITLE
Could not found view in xxx,xxx, please select view again

### ISSUE THREAD

**Issue by zhangxu2814** [eleme/UETool#72]
红米note 8 pro MIUI 11 9.12.6
Android 版本 10
me.ele:uetool-no-op:1.2.3

捕捉控件和相对位置会报错，网格栅栏和手术刀没发现该问题

**Comment by lu769257351** [comment]
一加也有同样问题

**Comment by JeasonWong** [comment]
@zhangxu2814 @lu769257351 请试下 1.2.9 版本

**Comment by Petterpx** [comment]
问题背景
compileSdkVersion: 30
targetSdkVersion 30
buildToolsVersion: "30.0.2"

me.ele:uetool-no-op:1.2.9
三星S10 SM-G9730
Android 11
存在此问题。

暂时解决方案
将Android sdk版本切回29,可以正常使用。
