### ISSUE TITLE
捕捉控件，修改选中的TextView的字色后会自己变回去

### ISSUE THREAD

**Issue by vierbom** [eleme/UETool#8]
#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by JeasonWong** [comment]
可以详细描述下修改字色后做了什么操作吗？或者方便截个图吗？

can you offer more description?

**Comment by vierbom** [comment]
修改之后又点了捕捉控件，现在没有问题了，之前展示菜单的位置放在application里，导致出现多个菜单的时候遇到这个问题，现在在进入activity之后才展示的，就没有遇到这问题了，只有多个菜单时候的截图
http://oxsk66d2q.bkt.clouddn.com/WechatIMG719.jpeg
