### ISSUE TITLE
Could not found view in xxx,xxx, please select view again (不兼容Android sdk 30)

### ISSUE THREAD

**Issue by Petterpx** [eleme/UETool#85]
问题背景
me.ele:uetool-no-op:1.2.9

compileSdkVersion: 30
targetSdkVersion 30
buildToolsVersion: "30.0.2"

三星S10 SM-G9730
Android 11
存在此问题。

暂时解决方案
将Android sdk版本切回29,可以正常使用

**Comment by lu769257351** [comment]
+1 设置30在Android 11的一加手机上无法使用

**Comment by 304847944** [comment]
+1 设置30在Android 11 的一加 9 手机上无法使用( 1.2.9 也是同样的)
