### ISSUE TITLE
version 1.3.2 cannot access https://jitpack.io, is it a private repo?

### ISSUE THREAD

**Issue by luciferldy** [eleme/UETool#87]
Could not determine the dependencies of task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.eleme:uetool-base:1.3.2.
     Required by:
         project :app > project :business:debug:impl
      > Could not resolve com.github.eleme:uetool-base:1.3.2.
         > Could not get resource 'https://jitpack.io/com/github/eleme/uetool-base/1.3.2/uetool-base-1.3.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/eleme/uetool-base/1.3.2/uetool-base-1.3.2.pom'. Received status code 401 from server: Unauthorized
* Try:

**Comment by Petterpx** [comment]
```
dependencies {
  debugImplementation 'com.github.eleme.UETool:uetool:1.3.2'
  debugImplementation 'com.github.eleme.UETool:uetool-base:1.3.2'
  releaseImplementation 'com.github.eleme.UETool:uetool-no-op:1.3.2'
  
  // if you want to show more attrs about Fresco's DraweeView
  debugImplementation 'com.github.eleme.UETool:uetool-fresco:1.3.2'
}
```

Gradle relies on address updates, readme forgot to synchronize, you can use the one I provided, waiting for merge PR

**Comment by luciferldy** [comment]
已收到，谢谢
