### ISSUE TITLE
Feature Request: 点击跳转的IDEA插件

### ISSUE THREAD

**Issue by Nstd** [eleme/UETool#92]
#### Description

希望能有一个IDEA联动的插件，APP上点击 Holder/ResName/OnClickListener 之类的value时，IDEA能跳转到对应的文件/代码位置。

初步想法是，电脑和手机处于同一网段，APP或IDEA插件开启一个服务器进行互相通信。APP中点击UETool面板对应资源字段时，发消息到IDEA插件服务器，IDEA插件再进行相应跳转。

**Comment by JeasonWong** [comment]
You can try to use this one, I think it can meet your requirement. https://github.com/bytedance/CodeLocator
